---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create semaphore file
      ansible.builtin.file:
        path: /tmp/testp.yml
        state: touch

    - name: Download playbook file from GitHub
      ansible.builtin.get_url:
        url: https://github.com/Sonu6659/playbook-testing/edit/main/
        dest: /tmp/testp.yml
      register: download_result
      ignore_errors: yes

    - name: Fail if download failed
      ansible.builtin.fail:
        msg: "Failed to download the playbook from GitHub"
      when: download_result.failed

    - name: Acquire semaphore lock
      ansible.builtin.shell:
        cmd: "flock -x /tmp/semaphore_file sleep 0"

    - name: Include downloaded playbook
      ansible.builtin.include_playbook: /tmp/testp.yml
    - name: Release semaphore lock
      ansible.builtin.shell:
        cmd: "flock -u /tmp/semaphore_file sleep 0"
