---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create semaphore file
      ansible.builtin.file:
        path: /home/sonu/singga/testp.yml
        state: touch

    - name: Acquire semaphore lock
      ansible.builtin.shell:
        cmd: "flock /tmp/semaphore_file sleep 0"

    - name: Print "Hello, World!"
      ansible.builtin.debug:
        msg: "Hello, World!"

    - name: Release semaphore lock
      ansible.builtin.shell:
        cmd: "flock -u /tmp/semaphore_file sleep 0"
